import type { AppEntry } from "./types";

export const SEED_APPS: AppEntry[] = [
  {
    slug: "dreamlog",
    title: "Dreamlog",
    tagline: "An AI journal that turns last night's dream into a surreal image.",
    description:
      "Write what you remember. Dreamlog stitches fragments into a single frame — a soft-edge collage that feels like the dream you almost caught. Swipe through your archive to watch your subconscious develop its own visual language.",
    liveUrl: "https://dreamlog.example",
    makerName: "Mira Okafor",
    makerHandle: "@miraokafor",
    tools: ["lovable", "claude-api"],
    category: "creative",
    upvotes: 284,
    palette: "dusk",
    motif: "wave",
    createdAt: "2026-03-04T10:00:00Z",
    seeded: true,
  },
  {
    slug: "pomopunk",
    title: "PomoPunk",
    tagline: "A cyberpunk pomodoro timer that rewards focus with generative city skylines.",
    description:
      "Every complete cycle adds a neon tower to your skyline. Break your streak and a district goes dark. By the end of the week your focus has drawn a city you can walk through in first-person.",
    liveUrl: "https://pomopunk.example",
    makerName: "Kenji Yao",
    makerHandle: "@kenjiyao",
    tools: ["v0", "cursor"],
    category: "productivity",
    upvotes: 512,
    palette: "ember",
    motif: "grid",
    createdAt: "2026-02-18T14:20:00Z",
    seeded: true,
  },
  {
    slug: "mothtrap",
    title: "Mothtrap",
    tagline: "A matchmaker for oddly specific hobbies. Find your one other person.",
    description:
      "Tell Mothtrap what you're weirdly into — 19th-century elevator patents, obscure Finnish death metal, tying knots you'll never use — and it finds the handful of people on earth who share the exact frequency.",
    liveUrl: "https://mothtrap.example",
    makerName: "Priya Venkatesh",
    makerHandle: "@priya.v",
    tools: ["cursor", "claude-code"],
    category: "social",
    upvotes: 176,
    palette: "violet",
    motif: "halftone",
    createdAt: "2026-03-12T09:30:00Z",
    seeded: true,
  },
  {
    slug: "quietmail",
    title: "Quietmail",
    tagline: "An email client that hides your inbox until you've replied to yesterday's.",
    description:
      "No badge counts. No red dots. Quietmail reveals exactly one message at a time, and the next one only unlocks when you've answered or consciously dismissed the last. A forcing function for a quieter day.",
    liveUrl: "https://quietmail.example",
    makerName: "Søren Krogh",
    makerHandle: "@sorenk",
    tools: ["bolt"],
    category: "productivity",
    upvotes: 402,
    palette: "menthol",
    motif: "stack",
    createdAt: "2026-01-29T11:15:00Z",
    seeded: true,
  },
  {
    slug: "overtone",
    title: "Overtone",
    tagline: "Generative ambient music composed live from your browser tabs.",
    description:
      "Every open tab becomes an instrument. A research doc is a pad, a YouTube tab is a delayed guitar, a spreadsheet is a slow pulse. Close something and the score thins out. It's oddly tidy, oddly beautiful.",
    liveUrl: "https://overtone.example",
    makerName: "Ana Beltrán",
    makerHandle: "@abeltran",
    tools: ["claude-code", "claude-api"],
    category: "creative",
    upvotes: 621,
    palette: "ocean",
    motif: "orbits",
    createdAt: "2026-02-02T18:45:00Z",
    seeded: true,
  },
  {
    slug: "palette-pigeon",
    title: "Palette Pigeon",
    tagline: "Color palettes sampled from real bird plumage. Upload a photo, get the plumage.",
    description:
      "Drop in a photograph — any bird, any lighting — and Palette Pigeon returns a six-swatch palette with scientific provenance, hex codes, and a downloadable .ase file. Designers love it. Ornithologists tolerate it.",
    liveUrl: "https://palettepigeon.example",
    makerName: "Theo Nakamura",
    makerHandle: "@theonkmr",
    tools: ["lovable", "v0"],
    category: "creative",
    upvotes: 338,
    palette: "saffron",
    motif: "halftone",
    createdAt: "2026-03-20T08:05:00Z",
    seeded: true,
  },
  {
    slug: "deadline",
    title: "Deadline",
    tagline: "A minimalist countdown that performs a small ritual as the hour approaches.",
    description:
      "Set one deadline. That's it. As the hour closes in, Deadline dims the room, slows its typography, and eventually holds a single pulsing dot. It is the most dramatic to-do app you will ever use exactly once per project.",
    liveUrl: "https://deadline.example",
    makerName: "Rue Agarwal",
    makerHandle: "@rueagar",
    tools: ["v0", "cursor"],
    category: "productivity",
    upvotes: 229,
    palette: "graphite",
    motif: "stack",
    createdAt: "2026-02-27T16:40:00Z",
    seeded: true,
  },
  {
    slug: "sideproject-fm",
    title: "Sideproject.fm",
    tagline: "Turns your week of GitHub commits into a two-minute podcast episode.",
    description:
      "Pipe in a repo. Sideproject.fm writes a warm, slightly embarrassed monologue about what you built, voiced by one of eight hosts (our favorite is Bev, the mildly concerned aunt). Publishes straight to your feed.",
    liveUrl: "https://sideproject.fm",
    makerName: "Jules Holloway",
    makerHandle: "@julesh",
    tools: ["cursor", "claude-api"],
    category: "dev-tools",
    upvotes: 487,
    palette: "citrus",
    motif: "wave",
    createdAt: "2026-03-08T12:00:00Z",
    seeded: true,
  },
  {
    slug: "garden",
    title: "Garden",
    tagline: "A markdown note graph with seasonal themes that shift through the year.",
    description:
      "Your notes grow, connect, and in winter, politely wilt. Garden redraws its palette with the solstices and renders old notes with the texture of whichever season they were written in. A gentler second brain.",
    liveUrl: "https://garden.example",
    makerName: "Wen Shi",
    makerHandle: "@wenshi",
    tools: ["replit-agent", "cursor"],
    category: "productivity",
    upvotes: 305,
    palette: "mint",
    motif: "orbits",
    createdAt: "2026-01-14T20:10:00Z",
    seeded: true,
  },
  {
    slug: "lost-and-found",
    title: "Lost & Found",
    tagline: "Scan a room with your phone. Ask it where you left the keys.",
    description:
      "A tiny AR app that continuously photographs your home as you walk through it, then answers questions in plain language: \"on the left corner of the kitchen counter, partly under a napkin, last seen twenty minutes ago.\"",
    liveUrl: "https://lostandfound.example",
    makerName: "Farrah Odusanya",
    makerHandle: "@farrahos",
    tools: ["bolt", "claude-api"],
    category: "ai",
    upvotes: 771,
    palette: "bloom",
    motif: "glyph",
    createdAt: "2026-03-29T07:55:00Z",
    seeded: true,
  },
  {
    slug: "crowd-math",
    title: "Crowd Math",
    tagline: "Split bills with drawings, not math. Circle what you ate.",
    description:
      "Drop in a photo of the receipt. Pass the phone around — each person circles their items with their finger. Crowd Math handles tax, tip, and the one guy who had two drinks. No one touches a calculator.",
    liveUrl: "https://crowdmath.example",
    makerName: "Lior Ben-Ari",
    makerHandle: "@liorba",
    tools: ["v0", "bolt"],
    category: "productivity",
    upvotes: 198,
    palette: "lilac",
    motif: "grid",
    createdAt: "2026-04-02T13:25:00Z",
    seeded: true,
  },
  {
    slug: "solstice",
    title: "Solstice",
    tagline: "Sun-aware screen tinting that nudges your circadian rhythm back on track.",
    description:
      "Solstice reads your latitude, the local weather, and the hour, then tints your entire OS to match the light outside. On overcast days it concedes; on clear evenings it dims to a quiet amber. You sleep better within a week.",
    liveUrl: "https://solstice.example",
    makerName: "Niko Pelekanos",
    makerHandle: "@nikopel",
    tools: ["cursor", "windsurf"],
    category: "dev-tools",
    upvotes: 256,
    palette: "concrete",
    motif: "wave",
    createdAt: "2026-02-10T06:50:00Z",
    seeded: true,
  },
];
